### ISSUE TITLE
Vote result slider bar

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#239]
Vote outcome: The slider bar is a little tricky to set an exact
number. Could just type in, select from a set of ranges or add
options like bipartisan vote, passed with minority of majority, etc.

**Comment by aaronrudkin** [comment]
This is sort of done. Typing is kind unwieldy and I think not very intuitive for most non powerusers. I did add radio boxes for all votes, supermajority (66+%) votes, majority votes, and minority votes. I didn't want to do "passed" / "failed" since that is question-specific and requires resolving the issues related to question types elsewhere. But this is a pretty good sort of quick way to calibrate to get just a few vote types.

Minority of majority would be difficult to implement since it requires a different type of data -- we could pre-calculate that data. I'm not sure how we'd surface it, probably not via the slider bar.
