### ISSUE TITLE
Party page design

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#274]
Could make it a simple table of parties with dates (could use something visual
like bars to show which ones were active at the same time), a map, the line chart
and space for a paragraph of history of the party

**Comment by aaronrudkin** [comment]
Yeah I think basically this should look more like what a band page lineup timeline looks like on Wikipedia, but rendered with tabular data or D3 instead of just a static SVG.

**Comment by aaronrudkin** [comment]
This is done (Jeff, this is what I mentioned on the issue the other day, about being able to sort by these fields).

Two loose ends here:

1. I don't really have a sensible way to display occasionally active parties. Like the label "Conservative Party" is used scattered times through history. If I display it as a solid bar, it looks way more powerful than it is. If I make it broken lines, like I do now, it drops detail. Currently the data just doesn't report the way I'd like it (i.e. it's not actually easy to see which specific congresses something was active in). Maybe the correct answer is to entirely suppress these labels, but I like that even less. Anyway, this is much denser and I think conveys information more readily than the old box method.

2. Want to actually attach years on the timeline bar, possibly in a subheader, so you can intuit around when parties started when you're looking at them.

Going to close for now but feel free to follow up with feedback in the closed issue.

Political science side note. Also interesting to me no one has used a minor party label since the 81st. Still a handful of independents and people-who-left-their-party people, but no one actually uses another label. It's not the lack of stable third parties that surprise me, it's the lack of people who are for all intents and purposes part of a major party but choose a minor party label anyway. There used to be a smattering of them. I guess people who do that today just pick "Independent". I wonder if this reflects post-war professionalization of media coverage and political parties, and the rapid upramp in required fundraising? Or just changes to ballot access laws and election stuff? Hmm.
