### ISSUE TITLE
Party chart data

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#278]
Would be great to be able to download the data for this chart
directly from this page (and maybe a png of the image since you
do that elsewhere).

**Comment by aaronrudkin** [comment]
I am closing this because there is generally an issue serializing SVGs to PNGs right now -- the actual libraries that do this are massive hacks. Below is what this currently looks like. Some of these issues are unfixable for now. The main issue to discuss this will be #256 when I have an update, and fixing that will fix this as well.

![parties_glance](https://user-images.githubusercontent.com/14701267/45850650-c13ae900-bceb-11e8-8138-9727f93a535b.png)
