### ISSUE TITLE
"Most conservative" plot calculations

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#313]
https://voteview.com/person/21300/kyrsten-sinema
https://voteview.com/person/40915/joe-manchin-iii

These both said "The most conservative Democrat of the 114th Congress". One member is in the House and the other's in the Senate, so I changed the writing to say that instead, but then I found this other one that _now_ says "more conservative than 67% of Democrats in the 114th Senate" but I think the 67% is not chamber-specific. So in this case, the original wording was correct. https://voteview.com/person/49308

114th Congress for each.

Am I misinterpeting something here?

**Comment by adamboche** [comment]
We've gotten several emails about this issue. I still don't understand if it's just a matter of rewriting the explanation or if there's a bug in the display.

**Comment by JeffreyBLewis** [comment]
Seems to me that we should make both quantities chamber specific.

**Comment by aaronrudkin** [comment]
Yeah this is weird. I will take a look at how this is working. I did think they were chamber specific.

**Comment by aaronrudkin** [comment]
Yeah, I see some of what's going on here. It's a bit of a mess -- complicated a bit that Luke grafted the party loyalty stuff on top of it. I haven't done any rewriting of the person page yet, but I'll fix this text first.

From what I can see there is some conflation of chamber specific / non-chamber specific measures, and also a rounding error that's going to impact the "most Conservative / Liberal" claim. I'll fix both.

**Comment by aaronrudkin** [comment]
The dev version now reflects accurate labels. The labels provided, are in order:

1. If the member is the most liberal/conservative in the entire congress, say that
2. If the member is the most liberal/conservative in the entire <chamber>, say that
3. If they are not superlative, then
* Report that they are more liberal/conservative than X% of the entire <chamber>
* Report that they are more liberal/conservative than X% of their party in <chamber>

And the histograms now reflect per-chamber NOMINATE distributions rather than across-congress.

So, examples:
http://128.97.229.160/person/21726/pramila-jayapal <-- Most liberal
http://128.97.229.160/person/21721/thomas-alexander-jr-garrett <-- Most conservative
http://128.97.229.160/person/41301/elizabeth-warren <-- Most liberal senator
http://128.97.229.160/person/41110/mike-lee <-- Most conservative senator
http://128.97.229.160/person/40915/joe-manchin-iii <-- Most conservative Democrat in the Senate
http://128.97.229.160/person/49703/susan-margaret-collins <-- Most liberal Republican in the Senate
http://128.97.229.160/person/21512/carlos-curbelo <-- A Liberal Republican in the House, but not the most Liberal
http://128.97.229.160/person/20343/timothy-j-ryan <-- No superlative at all.

**Comment by aaronrudkin** [comment]
Closing and we can address party loyalty stuff in #347
