### ISSUE TITLE
Small-party party loyalty

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#314]
For example, https://voteview.com/person/41300/angus-stanley-king-jr is an independent but disagrees with Sanders (the other independent) sometimes https://voteview.com/rollcall/RS1150213. Both have "party loyalty" of 100%, which can be surprising to users.

**Comment by aaronrudkin** [comment]
I think the correct answer here is simply not to report party loyalty for independents (because they are not meaningfully grouped together -- although it so happens that King and Sanders caucus together). The loyalty table is going to get a broader rewrite, but for now I will suppress this row for independents.
