### ISSUE TITLE
Announcements mailing list

### ISSUE THREAD

**Issue by adamboche** [voteview/WebVoteView#341]
We've had a request for a mailing list where people can sign up to be notified of changes. This is useful for people using automated procedures like grabbing data from a url, but would also be useful for announcing new features that may interest folks.

**Comment by aaronrudkin** [comment]
I added one of these. I'm linking it in here so we can verify that we're fine with the language. Currently the code just saves the information in a private file -- when I get the chance I'll make it use the SendGrid API directly so we never see the email. Any emails you currently have requesting this function (and which make clear the person is giving opt-in consent to signing up!!!!!) please add them to /var/www/voteview/model/email/newsletter_list.json (on production) for now. I have tested adding/removal. This does not do email verification and I don't use the email blacklist like I do with the contact form, since they can't actually contact us through the form.

https://vanguard.voteview.com/about
